### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Daggerpov** [Reeto29/Basketball_Bot_Discord#2]
- [x] IndexError with appending block stat, happens with Joe ingles, Luka Doncic, and Blake Griffin. Although, Luka Doncic was working earlier so this may be an issue caused by something other than what's happening on this line, idk.

![image](https://user-images.githubusercontent.com/53918934/125403299-62a2f600-e383-11eb-859a-458043489247.png)

**Comment by Daggerpov** [comment]
Oh so ig it works now no problems with Luka after I fixed the images...

**Comment by Daggerpov** [comment]
Ok so this is an issue when the player isn't a current one, and my image thing will then not work because of this problem. Additionally, my image thing doesn't work regardless for historic players.

**Comment by Daggerpov** [comment]
- [x] images not working for historic players, since my query only finds this and doesn't include the src tag:

![image](https://user-images.githubusercontent.com/53918934/125571384-05fc72c7-204f-403c-874e-505dd11c7c2b.png)

Doesn't matter whether I use different technologies, must be something with the website but when I inspect the full img tag shows: 

![image](https://user-images.githubusercontent.com/53918934/125571653-cca3a82e-42d0-4df3-a3cd-476d803b1430.png)

**Comment by Reeto29** [comment]
![image](https://user-images.githubusercontent.com/75958818/125866423-85266357-5518-4383-a9d3-ac981125d0c5.png)

![image](https://user-images.githubusercontent.com/75958818/125866442-ac2e266d-9448-4fa6-b089-83e087869894.png)
